name: CI Workflow

# - About ----------------------------------------------------------------------
# CI/CD GitHub Action to ensure that the application compiles successfully.
#
# The workflow will automate the compilation of the application using the debug
# configuration to ensure that the remote contains a working copy of the source
# code at all times. This prevents conflicts and blockers.
# ------------------------------------------------------------------------------

on:
  push:
    branches:
      - main
      - staging
      - 'topic/**'
      - 'rollback/**'
      - 'debug/**'
  pull_request:
    branches:
      - main 
      - staging
      - 'topic/**'
      - 'rollback/**'
      - 'debug/**'

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    timeout-minutes: 0.5
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0


  # validate:
  #   name: Validate
  #   needs: checkout
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5
  #   steps:
  #     - name: Check for Conventional Branches
  #       uses: ./.github/actions/conventional-branches


  assemble:
    name: Assemble Debug
    needs: checkout
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          
      - name: Set up Android
        uses: ./.github/actions/setup-android
        with:
          java-distros: 'temurin'
          java-version: '17'
          enable-secrets: 'true'
          enable-caching: 'true'

      - name: Assemble (Debug)
        shell: bash
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.console=plain
        run: |
          ./gradlew assembleDebug --no-daemon --stacktrace